package ar.uba.fi.feedlot.main

rule "adaptation until day 6"
when
    $a : Corral( dia < 6 )
then
    $a.setPorcentajePesoEnMS( 0.01 );
end


rule "adaptation between day 6 and day 14"
when
    $a : Corral( dia > 5 && < 15)
then
    $a.setPorcentajePesoEnMS( 0.02 );
end

rule "adaptation between day 15 and day 25"
when
    $a : Corral( dia > 14 && < 26)
then
    $a.setPorcentajePesoEnMS( 0.03 );
end

rule "adaptation from day 26 on"
when
    $a : Corral( dia > 26)
then
    $a.setPorcentajePesoEnMS( 0.029 );
end

rule "percentages until day 10"
when
    $a : Corral( dia < 11 )
then
    $a.getAlimento().setSiloSorgo( 0.48 );
    $a.getAlimento().setMaiz(0.38);
	$a.getAlimento().setExpellerSoja(0.124);
	$a.getAlimento().setPreMezclaMineral(0.016);
	$a.getAlimento().setMateriaSeca(0.62);
end


rule "percentages from day 11 to day 21"
when
    $a : Corral( dia > 10 && < 22 )
then
    $a.getAlimento().setSiloSorgo( 0.37 );
    $a.getAlimento().setMaiz(0.49);
	$a.getAlimento().setExpellerSoja(0.1225);
	$a.getAlimento().setPreMezclaMineral(0.0175);
	$a.getAlimento().setMateriaSeca(0.67);
end

rule "percentages from day 22 on"
when
    $a : Corral( dia > 21 )
then
    $a.getAlimento().setSiloSorgo( 0.265 );
    $a.getAlimento().setMaiz(0.598);
	$a.getAlimento().setExpellerSoja(0.12);
	$a.getAlimento().setPreMezclaMineral(0.017);
	$a.getAlimento().setMateriaSeca(0.73);
end

rule "gain weigth after adaptation"
when
    $a : Corral( dia > 25 )
then
    $a.setPesoActual(); 
end 

rule "cold factor"
when
    $a : Corral( temperatura < 20 )
then
    $a.setFactor(1.05); 
end 

rule "heat factor"
when
    $a : Corral( temperatura > 28 )
then
    $a.setFactor(0.95); 
end 

rule "no temperature factor"
when
    $a : Corral( temperatura >= 20 &&  <= 28)
then
    $a.setFactor(1.00); 
end 